### ISSUE TITLE
RabbitMQ localhost not working after running docker-compose

### ISSUE THREAD

**Issue by findkashif** [EdwinVW/pitstop#44]
RabbitMQ localhost not working after running docker-compose up command

Getting following error on login
`ReferenceError: disable_stats is not defined ReferenceError: disable_stats is not defined at Object.process (eval at compile (http://localhost:15672/js/ejs-1.0.min.js:1:6654), :6:29) at EJS.render (http://localhost:15672/js/ejs-1.0.min.js:1:1885) at format (http://localhost:15672/js/main.js:1086:21) at check_login (http://localhost:15672/js/main.js:89:34) at start_app_login (http://localhost:15672/js/main.js:75:9) at HTMLDocument. (http://localhost:15672/js/main.js:3:5) at e (http://localhost:15672/js/jquery-3.4.1.min.js:2:29453) at t (http://localhost:15672/js/jquery-3.4.1.min.js:2:29755)`

**Comment by EdwinVW** [comment]
Hi @findkashif. 

The RabbitMQ image is a standard image from Docker Hub. I've just removed the RabbitMQ docker image from my local machine and started Pitstop using `docker-compose up`. This automatically pulls the latest version of the image from docker hub. After everything was started, I was able to login to the management console and everything works as expected.

Maybe you can do the same to see whether this solves the issue: 

1. Stop all the containers (if they are still running): `docker-compose down`.
2. Remove the RabbitMQ docker image: `docker rmi rabbitmq:3-management`.
3. Restart the app: `docker-compose up`.
4. Check the logging for any errors and wait until everything is started.

Because it's a standard image pulled from Docker Hub, I won't be able to help with the issue unfortunately. Maybe it's an issue with your Docker installation!?

**Comment by EdwinVW** [comment]
Hi @findkashif. Can I close this issue?

**Comment by findkashif** [comment]
Yeah this issue get resolved automatically after sometime.
sometime it start working after few minutes and sometime it takes up to some hours too.
however we can close it. thanks for your help!

**Comment by robsiera** [comment]
I have the same error on Windows (not Docker) after upgrading from v3.6.6 to v3.8.2.
No additional information in the logfile.
Search in google for [rabbitmq "disable_stats is not defined"] only gives me this github page.

**Comment by ilgigrad** [comment]
Ihad the same error.
It can be solved by cleaning the browser's cache

**Comment by EdwinVW** [comment]
Thanks for the tip @ilgigrad !

**Comment by callmegod66** [comment]
> I have the same error on Windows (not Docker) after upgrading from v3.6.6 to v3.8.2. No additional information in the logfile. Search in google for [rabbitmq "disable_stats is not defined"] only gives me this github page.
> 
> EDIT: After stopping and starting the server **and** a Ctrl+F5 in the browser, the error disappeared

It really works.Thanks
