### ISSUE TITLE
All docker images deployment on Azure

### ISSUE THREAD

**Issue by findkashif** [EdwinVW/pitstop#47]
Hi @EdwinVW 

Do you have any plan to demonstrate - "Deployment and running all docker images on Azure portal".
Currently it is limited up to any local machine only.

Regards,
Kashif

**Comment by EdwinVW** [comment]
Hi @findkashif,

Because everything runs in docker containers, you can run Pitstop just as well in Azure. I have tested this once using an AKS (Azure Kubernetes Service) cluster. If you have k8s installed, you can switch between k8s clusters using the `kubectl config use-context` command. If you switch to your AKS cluster and start the application (using the `start-all` script), everything is spun up on the AKS cluster in the cloud. See the [k8s documentation](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/) for more info.
